spring:
  # 环境配置
  profiles:
    default: dev
  # 数据源
  datasource:
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL
    url: jdbc:mysql://#{mysql.host}:#{mysql.port}/#{mysql.database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    # 数据库连接用户名
    username: #{mysql.username}
    # 数据库连接密码
    password: #{mysql.password}